In [90]:
# Initial imports
import pandas as pd
import hvplot.pandas
from pathlib import Path

In [91]:
# Set the file path
file_path = Path('./Resources/sfo_neighborhoods_census_data.csv')

# Read in the CSV as a DataFrame
sfo_data_df = pd.read_csv(file_path)
sfo_data_df.head()

   year      neighborhood  sale_price_sqr_foot  housing_units  gross_rent
0  2010      Alamo Square           291.182945         372560        1239
1  2010        Anza Vista           267.932583         372560        1239
2  2010           Bayview           170.098665         372560        1239
3  2010  Buena Vista Park           347.394919         372560        1239
4  2010  Central Richmond           319.027623         372560        1239

In [92]:
#Use the groupby function to group the data by year. Aggregate the results by the mean of the groups

housing_units_by_year=sfo_data_df.groupby('year').mean()
housing_units_by_year

      sale_price_sqr_foot  housing_units  gross_rent
year
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

In [93]:
#Use the hvplot function to plot the housing_units_by_year DataFrame as a bar chart. 
#Make the x-axis represent the year and the y-axis represent the housing_units.
#Style and format the line plot to ensure a professionally styled visualization.

housing_units_by_year.hvplot.bar(
    title='Housing units SF 2010-2016', 
    x='year', 
    y='housing_units',
    xlabel="Year",
    ylabel="Housing units",
    ylim=(365000,385000)

    
)

:Bars   [year]   (housing_units)

What’s the overall trend in housing units over the period that you’re analyzing?

Housinng units are increasing with time.

In [94]:
#Group the data by year, and then average the results. 

housing_units_by_year=sfo_neighborhoods_census_data.groupby('year').mean()

housing_units_by_year

      sale_price_sqr_foot  housing_units  gross_rent
year
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

# What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

# Year 2010 is the lowest rent reported.

In [106]:
# Create a new DataFrame named prices_square_foot_by_year by filtering out the “housing_units” column. 
#The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

prices_square_foot_by_housing_units_by_year=[["sale_price_sqr_foot", "gross_rent"]]

prices_square_foot_by_year

      sale_price_sqr_foot  gross_rent
year
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

In [96]:
# Use hvPlot to plot the prices_square_foot_by_year DataFrame as a line plot.
# Hint This single plot will include lines for both sale_price_sqr_foot and gross_rent.
# Style and format the line plot to ensure a professionally styled visualization.

prices_square_foot_by_year.hvplot.line(
    title='Sale Price Per Square Foot and Avarage Gross Rent 2010-2016 - SF', 
    xlabel="Year",
    ylabel="Gross Rent/Sale Price per Foot"

)

:NdOverlay   [Variable]
   :Curve   [year]   (value)

Did any year experience a drop in the average sale price per square foot compared to the previous year? 

No. It seems to be growing graduately.

In [114]:
# Group by year and neighborhood and then create a new dataframe of the mean values
# Review the DataFrame

prices_by_year_by_neighborhood=sfo_data_df.groupby(['year','neighborhood']).mean()
prices_by_year_by_neighborhood

                             sale_price_sqr_foot  housing_units  gross_rent
year neighborhood
2010 Alamo Square                     291.182945       372560.0      1239.0
     Anza Vista                       267.932583       372560.0      1239.0
     Bayview                          170.098665       372560.0      1239.0
     Buena Vista Park                 347.394919       372560.0      1239.0
     Central Richmond                 319.027623       372560.0      1239.0
...                                          ...            ...         ...
2016 Telegraph Hill                   903.049771       384242.0      4390.0
     Twin Peaks                       970.085470       384242.0      4390.0
     Van Ness/ Civic Center           552.602567       384242.0      4390.0
     Visitacion Valley                328.319007       384242.0      4390.0
     Westwood Park                    631.195426       384242.0      4390.0

[397 rows x 3 columns]

In [115]:
# Filter out the housing_units
# Review the first and last five rows of the DataFrame

prices_by_year_by_neighborhood = prices_by_year_by_neighborhood[["sale_price_sqr_foot", "gross_rent"]]
prices_by_year_by_neighborhood

display(prices_by_year_by_neighborhood.head())
display(prices_by_year_by_neighborhood.tail())

                       sale_price_sqr_foot  gross_rent
year neighborhood
2010 Alamo Square               291.182945      1239.0
     Anza Vista                 267.932583      1239.0
     Bayview                    170.098665      1239.0
     Buena Vista Park           347.394919      1239.0
     Central Richmond           319.027623      1239.0

                             sale_price_sqr_foot  gross_rent
year neighborhood
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

In [118]:
# Use hvplot to create an interactive line plot of the average price per square foot
# The plot should have a dropdown selector for the neighborhood


prices_by_year_by_neighborhood.hvplot.line(
    groupby="neighborhood",
    title='Sale Price Per Square Foot and Avarage Gross Rent 2010-2016 - By Neighborhood', 
    xlabel="Year",
    ylabel="Gross Rent/Sale Price per Foot"

)

:DynamicMap   [neighborhood]
   :NdOverlay   [Variable]
      :Curve   [year]   (value)

In [99]:
#Compare the Average Sale Prices by Neighborhood
# Set the file path

file_path = Path('./Resources/neighborhoods_coordinates.csv')

In [100]:
# Read in the CSV as a DataFrame
neighborhood_locations_df = pd.read_csv(file_path,index_col="Neighborhood")
neighborhood_locations_df.head()

                       Lat         Lon
Neighborhood
Alamo Square     37.791012 -122.402100
Anza Vista       37.779598 -122.443451
Bayview          37.734670 -122.401060
Bayview Heights  37.728740 -122.410980
Bernal Heights   37.728630 -122.443050

In [131]:
#Using the original sfo_data_df Dataframe, create a DataFrame named all_neighborhood_info_df that groups the data by neighborhood. 
#Aggregate the results by the mean of the group.

all_neighborhood_info_df=sfo_data_df.groupby('neighborhood').mean()
all_neighborhood_info_df

,year,sale_price_sqr_foot,housing_units,gross_rent
neighborhood,,,,
Alamo Square,2013.000000,366.020712,378401.00,2817.285714
Anza Vista,2013.333333,373.382198,379050.00,3031.833333
Bayview,2012.000000,204.588623,376454.00,2318.400000
Bayview Heights,2015.000000,590.792839,382295.00,3739.000000
Bernal Heights,2013.500000,576.746488,379374.50,3080.333333
...,...,...,...,...
West Portal,2012.250000,498.488485,376940.75,2515.500000
Western Addition,2012.500000,307.562201,377427.50,2555.166667
Westwood Highlands,2012.000000,533.703935,376454.00,2250.500000
Westwood Park,2015.000000,687.087575,382295.00,3959.000000
Yerba Buena,2012.500000,576.709848,377427.50,2555.166667

In [157]:
# Using the Pandas `concat` function, join the 
# neighborhood_locations_df and the all_neighborhood_info_df DataFrame
# The axis of the concatenation is "columns".
# The concat function will automatially combine columns with
# identical information, while keeping the additional columns.
all_neighborhoods_df = pd.concat(
    [neighborhood_locations_df, all_neighborhood_info_df], 
    axis="columns",
    sort=False
)

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

,Lat,Lon,year,sale_price_sqr_foot,housing_units,gross_rent
Alamo Square,37.791012,-122.402100,2013.000000,366.020712,378401.0,2817.285714
Anza Vista,37.779598,-122.443451,2013.333333,373.382198,379050.0,3031.833333
Bayview,37.734670,-122.401060,2012.000000,204.588623,376454.0,2318.400000
Bayview Heights,37.728740,-122.410980,2015.000000,590.792839,382295.0,3739.000000
Bernal Heights,37.728630,-122.443050,NaN,NaN,NaN,NaN

,Lat,Lon,year,sale_price_sqr_foot,housing_units,gross_rent
Yerba Buena,37.79298,-122.39636,2012.5,576.709848,377427.5,2555.166667
Bernal Heights,NaN,NaN,2013.5,576.746488,379374.5,3080.333333
Downtown,NaN,NaN,2013.0,391.434378,378401.0,2817.285714
Ingleside,NaN,NaN,2012.5,367.895144,377427.5,2509.000000
Outer Richmond,NaN,NaN,2013.0,473.900773,378401.0,2817.285714

In [158]:
# Call the dropna function to remove any neighborhoods that do not have data
all_neighborhoods_df = all_neighborhoods_df.dropna()

display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

,Lat,Lon,year,sale_price_sqr_foot,housing_units,gross_rent
Alamo Square,37.791012,-122.402100,2013.000000,366.020712,378401.0,2817.285714
Anza Vista,37.779598,-122.443451,2013.333333,373.382198,379050.0,3031.833333
Bayview,37.734670,-122.401060,2012.000000,204.588623,376454.0,2318.400000
Bayview Heights,37.728740,-122.410980,2015.000000,590.792839,382295.0,3739.000000
Buena Vista Park,37.768160,-122.439330,2012.833333,452.680591,378076.5,2698.833333

,Lat,Lon,year,sale_price_sqr_foot,housing_units,gross_rent
West Portal,37.74026,-122.463880,2012.25,498.488485,376940.75,2515.500000
Western Addition,37.79298,-122.435790,2012.50,307.562201,377427.50,2555.166667
Westwood Highlands,37.73470,-122.456854,2012.00,533.703935,376454.00,2250.500000
Westwood Park,37.73415,-122.457000,2015.00,687.087575,382295.00,3959.000000
Yerba Buena,37.79298,-122.396360,2012.50,576.709848,377427.50,2555.166667

In [168]:
# Rename the "index" column as "Neighborhood" for use in the Visualization

all_neighborhoods_df.rename_axis('Neighborhood')
all_neighborhoods_df

,Lat,Lon,year,sale_price_sqr_foot,housing_units,gross_rent
Alamo Square,37.791012,-122.402100,2013.000000,366.020712,378401.00,2817.285714
Anza Vista,37.779598,-122.443451,2013.333333,373.382198,379050.00,3031.833333
Bayview,37.734670,-122.401060,2012.000000,204.588623,376454.00,2318.400000
Bayview Heights,37.728740,-122.410980,2015.000000,590.792839,382295.00,3739.000000
Buena Vista Park,37.768160,-122.439330,2012.833333,452.680591,378076.50,2698.833333
...,...,...,...,...,...,...
West Portal,37.740260,-122.463880,2012.250000,498.488485,376940.75,2515.500000
Western Addition,37.792980,-122.435790,2012.500000,307.562201,377427.50,2555.166667
Westwood Highlands,37.734700,-122.456854,2012.000000,533.703935,376454.00,2250.500000
Westwood Park,37.734150,-122.457000,2015.000000,687.087575,382295.00,3959.000000
Yerba Buena,37.792980,-122.396360,2012.500000,576.709848,377427.50,2555.166667

In [167]:
# Create a plot to analyze neighborhood info
map_plot = all_neighborhoods_df.hvplot.points(
    'Lon', 
    'Lat', 
    geo=True, 
    size = 'sale_price_sqr_foot',
    color='gross_rent',
    tiles='OSM',
    frame_width = 700,
    frame_height = 500
    )

map_plot

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot)

Question: Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

Answer: The highest rent is Mount Davidson and the highest price per square foot is Montgomery street.

Compose Your Data Story

Based on the visualizations that you have created, compose a data story that synthesizes your analysis by answering the following questions:

Question: How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

Answer: As the price per sq ft goes up, the gross rent goes up as well

Question: What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

Answer: The proposed strategy is to focus on the properties with smaller price per sq ft and and higher gross rent like on Silver ave